# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --color=yes -e 'using InteractiveUtils; versioninfo(); import Pkg; Pkg.clone(pwd())'
  - CGBITMAP_CONTEXT_LOG_ERRORS=1 julia --color=yes --check-bounds=yes -e 'import Pkg; Pkg.test("QuartzImageIO"; coverage=true)'
after_success:
  - julia -e 'import Pkg; cd(Pkg.dir("QuartzImageIO")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
